# Change these first
owner: ourbits # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Ourbits
    url: https://ourbits.club/torrentrss.php?passkey=
  - name: Ourbits Ticket
    url: https://ticket.ourbits.club/
  - name: Ourhelp API
    url: https://api.ourhelp.club/
    headers:
      - "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  favicon: https://ourbits.club/favicon.ico
  name: OurBits Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
